In [1]:
import sqlite3

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
db_path = "Dirigo.sqlite"
conn = sqlite3.connect(db_path)

In [4]:
df_cargo = pd.read_sql_query("SELECT * FROM OCEL_Cargo",conn)
df_truck = pd.read_sql_query("SELECT * FROM OCEL_Truck",conn)
df_pickup = pd.read_sql_query("SELECT * FROM OCEL_PickupPLan",conn)
df_e2o = pd.read_sql_query("SELECT * FROM OCEL_E2O",conn)
df_o2o = pd.read_sql_query("SELECT * FROM OCEL_O2O", conn)
df_events = pd.read_sql_query("SELECT * FROM OCEL_Events",conn)

conn.close()

In [5]:
df_events

,Event_id,Timestamp,Activity
0,Lodge_Pcp44,2024-04-29 08:04:44,Lodge Pickup Plan
1,Lodge_Pcp87,2024-04-29 08:12:32,Lodge Pickup Plan
2,Lodge_Pcp48,2024-04-29 08:31:44,Lodge Pickup Plan
3,Lodge_Pcp55,2024-04-29 08:32:30,Lodge Pickup Plan
4,Lodge_Pcp69,2024-04-29 08:39:46,Lodge Pickup Plan
...,...,...,...
1495,eval_trs_exit_tr49_Pcp70,2024-05-03 15:38:46,Evaluate the Truck Exit
1496,weigh_loaded_truck_Pcp70_tr29,2024-05-03 15:43:38,Weigh the Loaded Truck
1497,print_w_ticket_Pcp70_tr29,2024-05-03 15:47:10,Print the Weighing Ticket
1498,input_tally_sheet_Pcp70_tr29,2024-05-03 15:47:10,Input the Tally Sheet
1499,eval_trs_exit_tr29_Pcp70,2024-05-03 15:48:23,Evaluate the Truck Exit

In [6]:
df_o2o

,Source_object_id,Target_object_id,O2O_qualifier,Timestamp
0,Pcp44,Cr2,Lodged pickup plan for cargo,2024-04-29 08:04:44
1,Pcp87,Cr9,Lodged pickup plan for cargo,2024-04-29 08:12:32
2,Pcp48,Cr20,Lodged pickup plan for cargo,2024-04-29 08:31:44
3,Pcp55,Cr13,Lodged pickup plan for cargo,2024-04-29 08:32:30
4,Pcp69,Cr7,Lodged pickup plan for cargo,2024-04-29 08:39:46
...,...,...,...,...
495,tr29,Pcp51,Dropped truck from pickup plan,2024-05-02 15:18:40
496,tr29,Pcp70,Assigned truck for pickup plan,2024-05-03 15:08:59
497,tr49,Pcp70,Assigned truck for pickup plan,2024-05-03 15:09:23
498,tr49,Pcp70,Dropped truck from pickup plan,2024-05-03 15:38:46
499,tr29,Pcp70,Dropped truck from pickup plan,2024-05-03 15:48:23

In [7]:
combined_events_e2o = pd.merge(df_events, df_e2o, on="Event_id", how= 'inner')
combined_events_e2o

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier
0,Lodge_Pcp44,2024-04-29 08:04:44,Lodge Pickup Plan,Pcp44,Pickup plan being lodged
1,Lodge_Pcp44,2024-04-29 08:04:44,Lodge Pickup Plan,Cr2,Cargo being scheduled for pickup
2,Lodge_Pcp87,2024-04-29 08:12:32,Lodge Pickup Plan,Pcp87,Pickup plan being lodged
3,Lodge_Pcp87,2024-04-29 08:12:32,Lodge Pickup Plan,Cr9,Cargo being scheduled for pickup
4,Lodge_Pcp48,2024-04-29 08:31:44,Lodge Pickup Plan,Pcp48,Pickup plan being lodged
...,...,...,...,...,...
1595,eval_trs_exit_tr49_Pcp70,2024-05-03 15:38:46,Evaluate the Truck Exit,tr49,Truck being evaluated for exit
1596,weigh_loaded_truck_Pcp70_tr29,2024-05-03 15:43:38,Weigh the Loaded Truck,tr29,Loaded truck getting weighed
1597,print_w_ticket_Pcp70_tr29,2024-05-03 15:47:10,Print the Weighing Ticket,tr29,Truck receiving weighing ticket
1598,input_tally_sheet_Pcp70_tr29,2024-05-03 15:47:10,Input the Tally Sheet,tr29,Truck being recorded on tally sheet
1599,eval_trs_exit_tr29_Pcp70,2024-05-03 15:48:23,Evaluate the Truck Exit,tr29,Truck being evaluated for exit

In [8]:
df_truck

,Object_id,Timestamp,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight
0,tr46,2024-03-04 00:00:00,None,None,None,271FSE,6.0,0.0,Available,0.0
1,tr28,2024-03-04 00:00:00,None,None,None,157LCX,4.0,0.0,Available,0.0
2,tr5,2024-03-04 00:00:00,None,None,None,012CRA,6.0,0.0,Available,0.0
3,tr27,2024-03-04 00:00:00,None,None,None,764KIO,4.0,0.0,Available,0.0
4,tr41,2024-03-04 00:00:00,None,None,None,055DSW,4.0,0.0,Available,0.0
...,...,...,...,...,...,...,...,...,...,...
1445,tr29,2024-05-03 15:22:06,Truck Weight,None,None,None,NaN,NaN,None,12136.1
1446,tr49,2024-05-03 15:33:13,Truck Weight,None,None,None,NaN,NaN,None,17593.0
1447,tr29,2024-05-03 15:43:38,Truck Weight,None,None,None,NaN,NaN,None,17594.9
1448,tr49,2024-05-03 15:50:06,Truck Status,None,None,None,NaN,NaN,Available,NaN
1449,tr29,2024-05-03 15:56:08,Truck Status,None,None,None,NaN,NaN,Available,NaN

In [9]:
truck_merged_df = pd.merge(combined_events_e2o, df_truck, on=['Object_id', 'Timestamp'],how = 'outer')
truck_merged_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight
0,Lodge_Pcp18,2024-04-29 08:46:20,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lodge_Pcp53,2024-04-29 11:17:06,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lodge_Pcp42,2024-04-29 13:23:11,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lodge_Pcp93,2024-04-29 16:19:27,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Lodge_Pcp57,2024-04-30 08:27:54,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2445,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9
2446,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2447,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2448,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2449,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN

In [10]:
pp_merged_df = pd.merge(truck_merged_df,df_pickup, on=['Object_id', 'Timestamp'],how = 'outer')
pp_merged_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field_x,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Ocel_changed_field_y,CargoID,Num of trucks,Total pickup weight
0,Lodge_Pcp18,2024-04-29 08:46:20,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lodge_Pcp53,2024-04-29 11:17:06,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lodge_Pcp42,2024-04-29 13:23:11,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lodge_Pcp93,2024-04-29 16:19:27,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Lodge_Pcp57,2024-04-30 08:27:54,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2445,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN
2446,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2447,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2448,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2449,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN

In [11]:
lodge_merged_filtered = pp_merged_df[pp_merged_df['Activity']=='Lodge Pickup Plan']
lodge_merged_filtered

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field_x,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Ocel_changed_field_y,CargoID,Num of trucks,Total pickup weight
0,Lodge_Pcp18,2024-04-29 08:46:20,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lodge_Pcp53,2024-04-29 11:17:06,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lodge_Pcp42,2024-04-29 13:23:11,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lodge_Pcp93,2024-04-29 16:19:27,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Lodge_Pcp57,2024-04-30 08:27:54,Lodge Pickup Plan,Cr1,Cargo being scheduled for pickup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Lodge_Pcp95,2024-04-29 15:20:33,Lodge Pickup Plan,Pcp95,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Cr15,2.0,10694.5
196,Lodge_Pcp96,2024-04-29 17:13:30,Lodge Pickup Plan,Pcp96,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Cr8,2.0,11864.1
197,Lodge_Pcp97,2024-04-29 15:14:43,Lodge Pickup Plan,Pcp97,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Cr12,2.0,10470.6
198,Lodge_Pcp98,2024-04-29 10:07:21,Lodge Pickup Plan,Pcp98,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Cr9,2.0,11242.8
199,Lodge_Pcp99,2024-04-29 15:33:22,Lodge Pickup Plan,Pcp99,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Cr18,2.0,11566.6

In [12]:
lodge_merged_filtered['Cargo ID'] = lodge_merged_filtered['Cargo ID'].fillna(lodge_merged_filtered['CargoID'])
pcps = lodge_merged_filtered['Pickup Plan ID'].isna() & lodge_merged_filtered['Object_id'].str.startswith('Pcp')
lodge_merged_filtered.loc[pcps, 'Pickup Plan ID'] = lodge_merged_filtered.loc[pcps, 'Object_id']
lodge_merged_filtered = lodge_merged_filtered[~lodge_merged_filtered['Object_id'].str.startswith('Cr', na=False)]
lodge_merged_filtered.drop(columns=['CargoID','Ocel_changed_field_y'], inplace=True)
lodge_merged_filtered.rename(columns={'Ocel_changed_field_x':'Ocel_changed_field'}, inplace=True)
lodge_merged_filtered

/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/3286718363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lodge_merged_filtered['Cargo ID'] = lodge_merged_filtered['Cargo ID'].fillna(lodge_merged_filtered['CargoID'])
/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/3286718363.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lodge_merged_filtered.drop(columns=['CargoID','Ocel_changed_field_y'], inplace=True)
/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/3286718363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lodge_merged_filtered.rename(columns={'Ocel_changed_field_x':'Ocel_changed_field'}, inplace=True)

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight
100,Lodge_Pcp1,2024-04-29 16:02:43,Lodge Pickup Plan,Pcp1,Pickup plan being lodged,NaN,Pcp1,Cr4,NaN,NaN,NaN,NaN,NaN,2.0,10278.5
101,Lodge_Pcp10,2024-04-29 10:36:01,Lodge Pickup Plan,Pcp10,Pickup plan being lodged,NaN,Pcp10,Cr5,NaN,NaN,NaN,NaN,NaN,2.0,10411.3
102,Lodge_Pcp100,2024-04-29 11:34:06,Lodge Pickup Plan,Pcp100,Pickup plan being lodged,NaN,Pcp100,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10424.2
103,Lodge_Pcp11,2024-04-29 17:13:44,Lodge Pickup Plan,Pcp11,Pickup plan being lodged,NaN,Pcp11,Cr19,NaN,NaN,NaN,NaN,NaN,2.0,10252.9
104,Lodge_Pcp12,2024-04-29 16:39:13,Lodge Pickup Plan,Pcp12,Pickup plan being lodged,NaN,Pcp12,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,10420.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Lodge_Pcp95,2024-04-29 15:20:33,Lodge Pickup Plan,Pcp95,Pickup plan being lodged,NaN,Pcp95,Cr15,NaN,NaN,NaN,NaN,NaN,2.0,10694.5
196,Lodge_Pcp96,2024-04-29 17:13:30,Lodge Pickup Plan,Pcp96,Pickup plan being lodged,NaN,Pcp96,Cr8,NaN,NaN,NaN,NaN,NaN,2.0,11864.1
197,Lodge_Pcp97,2024-04-29 15:14:43,Lodge Pickup Plan,Pcp97,Pickup plan being lodged,NaN,Pcp97,Cr12,NaN,NaN,NaN,NaN,NaN,2.0,10470.6
198,Lodge_Pcp98,2024-04-29 10:07:21,Lodge Pickup Plan,Pcp98,Pickup plan being lodged,NaN,Pcp98,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,11242.8
199,Lodge_Pcp99,2024-04-29 15:33:22,Lodge Pickup Plan,Pcp99,Pickup plan being lodged,NaN,Pcp99,Cr18,NaN,NaN,NaN,NaN,NaN,2.0,11566.6

In [13]:
non_lodge_merged_filtered = pp_merged_df[pp_merged_df['Activity']!='Lodge Pickup Plan']
non_lodge_merged_filtered.drop(columns=['CargoID','Ocel_changed_field_y'], inplace=True)
non_lodge_merged_filtered.rename(columns={'Ocel_changed_field_x':'Ocel_changed_field'}, inplace=True)

/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/1081913683.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_lodge_merged_filtered.drop(columns=['CargoID','Ocel_changed_field_y'], inplace=True)
/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/1081913683.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_lodge_merged_filtered.rename(columns={'Ocel_changed_field_x':'Ocel_changed_field'}, inplace=True)

In [14]:
lodge_merged_trucks = pd.concat([lodge_merged_filtered,non_lodge_merged_filtered]).reset_index(drop=True)
lodge_merged_trucks

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight
0,Lodge_Pcp1,2024-04-29 16:02:43,Lodge Pickup Plan,Pcp1,Pickup plan being lodged,NaN,Pcp1,Cr4,NaN,NaN,NaN,NaN,NaN,2.0,10278.5
1,Lodge_Pcp10,2024-04-29 10:36:01,Lodge Pickup Plan,Pcp10,Pickup plan being lodged,NaN,Pcp10,Cr5,NaN,NaN,NaN,NaN,NaN,2.0,10411.3
2,Lodge_Pcp100,2024-04-29 11:34:06,Lodge Pickup Plan,Pcp100,Pickup plan being lodged,NaN,Pcp100,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10424.2
3,Lodge_Pcp11,2024-04-29 17:13:44,Lodge Pickup Plan,Pcp11,Pickup plan being lodged,NaN,Pcp11,Cr19,NaN,NaN,NaN,NaN,NaN,2.0,10252.9
4,Lodge_Pcp12,2024-04-29 16:39:13,Lodge Pickup Plan,Pcp12,Pickup plan being lodged,NaN,Pcp12,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,10420.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN
2346,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2347,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2348,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2349,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN

In [15]:
cargo_merged_rest = pd.merge(lodge_merged_trucks, df_cargo, on=['Object_id', 'Timestamp'], how='outer')
cargo_merged_rest

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field_x,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Ocel_changed_field_y,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,NaN,2024-03-04 00:00:00,NaN,Cr1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Rice,120122.9,Sil14
1,NaN,2024-04-29 08:46:20,NaN,Cr1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cargo stock weight(scheduled),None,109508.7,None
2,NaN,2024-04-29 11:17:06,NaN,Cr1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cargo stock weight(scheduled),None,99073.1,None
3,NaN,2024-04-29 13:23:11,NaN,Cr1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cargo stock weight(scheduled),None,87666.2,None
4,NaN,2024-04-29 16:19:27,NaN,Cr1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cargo stock weight(scheduled),None,76748.4,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN,NaN
2466,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2468,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2469,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
cargo_merged_rest['Ocel_changed_field_x'] = cargo_merged_rest['Ocel_changed_field_x'].fillna(cargo_merged_rest['Ocel_changed_field_y'])
cargo_merged_rest.drop(columns=['Ocel_changed_field_y'], inplace=True)
cargo_merged_rest.rename(columns={'Ocel_changed_field_x':'Ocel_changed_field'}, inplace=True)
cargo_merged_rest

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,NaN,2024-03-04 00:00:00,NaN,Cr1,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,120122.9,Sil14
1,NaN,2024-04-29 08:46:20,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,109508.7,None
2,NaN,2024-04-29 11:17:06,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,99073.1,None
3,NaN,2024-04-29 13:23:11,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,87666.2,None
4,NaN,2024-04-29 16:19:27,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,76748.4,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN
2466,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2468,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2469,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
lodge_ts = cargo_merged_rest[cargo_merged_rest['Activity'] == 'Lodge Pickup Plan']['Timestamp'].unique()
len(lodge_ts)

100

In [18]:
df_update_part = cargo_merged_rest[(cargo_merged_rest['Activity'] == 'Lodge Pickup Plan') | ((cargo_merged_rest['Event_id'].isna()) & (cargo_merged_rest['Timestamp'].isin(lodge_ts)) & cargo_merged_rest['Object_id'].str.startswith('Cr'))].copy()
df_update_part

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
1,NaN,2024-04-29 08:46:20,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,109508.7,None
2,NaN,2024-04-29 11:17:06,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,99073.1,None
3,NaN,2024-04-29 13:23:11,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,87666.2,None
4,NaN,2024-04-29 16:19:27,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,76748.4,None
5,NaN,2024-04-30 08:27:54,NaN,Cr1,NaN,Cargo stock weight(scheduled),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,64995.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Lodge_Pcp95,2024-04-29 15:20:33,Lodge Pickup Plan,Pcp95,Pickup plan being lodged,NaN,Pcp95,Cr15,NaN,NaN,NaN,NaN,NaN,2.0,10694.5,NaN,NaN,NaN
216,Lodge_Pcp96,2024-04-29 17:13:30,Lodge Pickup Plan,Pcp96,Pickup plan being lodged,NaN,Pcp96,Cr8,NaN,NaN,NaN,NaN,NaN,2.0,11864.1,NaN,NaN,NaN
217,Lodge_Pcp97,2024-04-29 15:14:43,Lodge Pickup Plan,Pcp97,Pickup plan being lodged,NaN,Pcp97,Cr12,NaN,NaN,NaN,NaN,NaN,2.0,10470.6,NaN,NaN,NaN
218,Lodge_Pcp98,2024-04-29 10:07:21,Lodge Pickup Plan,Pcp98,Pickup plan being lodged,NaN,Pcp98,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,11242.8,NaN,NaN,NaN
219,Lodge_Pcp99,2024-04-29 15:33:22,Lodge Pickup Plan,Pcp99,Pickup plan being lodged,NaN,Pcp99,Cr18,NaN,NaN,NaN,NaN,NaN,2.0,11566.6,NaN,NaN,NaN

In [19]:
df_rest = cargo_merged_rest.drop(df_update_part.index)
df_rest

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,NaN,2024-03-04 00:00:00,NaN,Cr1,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,120122.9,Sil14
6,NaN,2024-03-04 00:00:00,NaN,Cr10,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,112195.7,Sil16
13,NaN,2024-03-04 00:00:00,NaN,Cr11,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,122522.8,Sil19
19,NaN,2024-03-04 00:00:00,NaN,Cr12,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,115248.0,Sil6
25,NaN,2024-03-04 00:00:00,NaN,Cr13,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,149062.7,Sil9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN
2466,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2468,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2469,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
lodge_mask = df_update_part['Activity'] == 'Lodge Pickup Plan'
lodge_idxs = df_update_part[lodge_mask].index
filler_df = df_update_part[~lodge_mask]

In [21]:
for idx in lodge_idxs:
    ts = df_update_part.at[idx, 'Timestamp']
    matching_rows = filler_df[filler_df['Timestamp'] == ts]
    
    for _, mrow in matching_rows.iterrows():
        for col in cargo_merged_rest.columns:
            val = df_update_part.at[idx, col]
            if pd.isna(val) or val in ['', 'None', 'nan', 'NaN']:
                if not pd.isna(mrow[col]) and mrow[col] not in ['', 'None', 'nan', 'NaN']:
                    df_update_part.at[idx, col] = mrow[col]

In [22]:
df_update_part[lodge_mask]

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
120,Lodge_Pcp1,2024-04-29 16:02:43,Lodge Pickup Plan,Pcp1,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp1,Cr4,NaN,NaN,NaN,NaN,NaN,2.0,10278.5,NaN,102064.7,NaN
121,Lodge_Pcp10,2024-04-29 10:36:01,Lodge Pickup Plan,Pcp10,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp10,Cr5,NaN,NaN,NaN,NaN,NaN,2.0,10411.3,NaN,106168.0,NaN
122,Lodge_Pcp100,2024-04-29 11:34:06,Lodge Pickup Plan,Pcp100,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp100,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10424.2,NaN,91717.3,NaN
123,Lodge_Pcp11,2024-04-29 17:13:44,Lodge Pickup Plan,Pcp11,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp11,Cr19,NaN,NaN,NaN,NaN,NaN,2.0,10252.9,NaN,93563.1,NaN
124,Lodge_Pcp12,2024-04-29 16:39:13,Lodge Pickup Plan,Pcp12,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp12,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,10420.8,NaN,100464.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Lodge_Pcp95,2024-04-29 15:20:33,Lodge Pickup Plan,Pcp95,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp95,Cr15,NaN,NaN,NaN,NaN,NaN,2.0,10694.5,NaN,61411.3,NaN
216,Lodge_Pcp96,2024-04-29 17:13:30,Lodge Pickup Plan,Pcp96,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp96,Cr8,NaN,NaN,NaN,NaN,NaN,2.0,11864.1,NaN,55406.7,NaN
217,Lodge_Pcp97,2024-04-29 15:14:43,Lodge Pickup Plan,Pcp97,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp97,Cr12,NaN,NaN,NaN,NaN,NaN,2.0,10470.6,NaN,72386.3,NaN
218,Lodge_Pcp98,2024-04-29 10:07:21,Lodge Pickup Plan,Pcp98,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp98,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,11242.8,NaN,121871.9,NaN
219,Lodge_Pcp99,2024-04-29 15:33:22,Lodge Pickup Plan,Pcp99,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp99,Cr18,NaN,NaN,NaN,NaN,NaN,2.0,11566.6,NaN,99275.3,NaN

In [23]:
df_final = pd.concat([df_update_part[lodge_mask], df_rest], ignore_index=True)
df_final

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,Lodge_Pcp1,2024-04-29 16:02:43,Lodge Pickup Plan,Pcp1,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp1,Cr4,NaN,NaN,NaN,NaN,NaN,2.0,10278.5,NaN,102064.7,NaN
1,Lodge_Pcp10,2024-04-29 10:36:01,Lodge Pickup Plan,Pcp10,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp10,Cr5,NaN,NaN,NaN,NaN,NaN,2.0,10411.3,NaN,106168.0,NaN
2,Lodge_Pcp100,2024-04-29 11:34:06,Lodge Pickup Plan,Pcp100,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp100,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10424.2,NaN,91717.3,NaN
3,Lodge_Pcp11,2024-04-29 17:13:44,Lodge Pickup Plan,Pcp11,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp11,Cr19,NaN,NaN,NaN,NaN,NaN,2.0,10252.9,NaN,93563.1,NaN
4,Lodge_Pcp12,2024-04-29 16:39:13,Lodge Pickup Plan,Pcp12,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp12,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,10420.8,NaN,100464.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN
2366,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2367,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2368,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2369,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_final.loc[(df_final['Ocel_changed_field'].isna()) & df_final['LPT'].notna(), 'Activity'] = 'Review the Truck Information'
df_final[df_final['Activity']== 'Review the Truck Information']

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
120,NaN,2024-03-04 00:00:00,Review the Truck Information,tr1,NaN,NaN,None,None,779BOG,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
165,NaN,2024-03-04 00:00:00,Review the Truck Information,tr10,NaN,NaN,None,None,622SCZ,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
199,NaN,2024-03-04 00:00:00,Review the Truck Information,tr11,NaN,NaN,None,None,720QYQ,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
244,NaN,2024-03-04 00:00:00,Review the Truck Information,tr12,NaN,NaN,None,None,710YJQ,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
289,NaN,2024-03-04 00:00:00,Review the Truck Information,tr13,NaN,NaN,None,None,751GPH,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
345,NaN,2024-03-04 00:00:00,Review the Truck Information,tr14,NaN,NaN,None,None,704VGQ,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
390,NaN,2024-03-04 00:00:00,Review the Truck Information,tr15,NaN,NaN,None,None,847TSW,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
435,NaN,2024-03-04 00:00:00,Review the Truck Information,tr16,NaN,NaN,None,None,681JLZ,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
469,NaN,2024-03-04 00:00:00,Review the Truck Information,tr17,NaN,NaN,None,None,581DYE,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
503,NaN,2024-03-04 00:00:00,Review the Truck Information,tr18,NaN,NaN,None,None,926VFT,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
548,NaN,2024-03-04 00:00:00,Review the Truck Information,tr19,NaN,NaN,None,None,768QPS,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
593,NaN,2024-03-04 00:00:00,Review the Truck Information,tr2,NaN,NaN,None,None,433XVW,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
627,NaN,2024-03-04 00:00:00,Review the Truck Information,tr20,NaN,NaN,None,None,622MSX,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
661,NaN,2024-03-04 00:00:00,Review the Truck Information,tr21,NaN,NaN,None,None,275FJS,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
706,NaN,2024-03-04 00:00:00,Review the Truck Information,tr22,NaN,NaN,None,None,534VKG,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
773,NaN,2024-03-04 00:00:00,Review the Truck Information,tr23,NaN,NaN,None,None,152SGS,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
840,NaN,2024-03-04 00:00:00,Review the Truck Information,tr24,NaN,NaN,None,None,745QOR,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
885,NaN,2024-03-04 00:00:00,Review the Truck Information,tr25,NaN,NaN,None,None,935YUF,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
941,NaN,2024-03-04 00:00:00,Review the Truck Information,tr26,NaN,NaN,None,None,968MEX,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
986,NaN,2024-03-04 00:00:00,Review the Truck Information,tr27,NaN,NaN,None,None,764KIO,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1031,NaN,2024-03-04 00:00:00,Review the Truck Information,tr28,NaN,NaN,None,None,157LCX,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1076,NaN,2024-03-04 00:00:00,Review the Truck Information,tr29,NaN,NaN,None,None,199LWF,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1154,NaN,2024-03-04 00:00:00,Review the Truck Information,tr3,NaN,NaN,None,None,747FJX,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1221,NaN,2024-03-04 00:00:00,Review the Truck Information,tr30,NaN,NaN,None,None,322GGS,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1277,NaN,2024-03-04 00:00:00,Review the Truck Information,tr31,NaN,NaN,None,None,702XFC,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1344,NaN,2024-03-04 00:00:00,Review the Truck Information,tr32,NaN,NaN,None,None,380DUE,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1378,NaN,2024-03-04 00:00:00,Review the Truck Information,tr33,NaN,NaN,None,None,823MWT,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1412,NaN,2024-03-04 00:00:00,Review the Truck Information,tr34,NaN,NaN,None,None,341KDU,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1446,NaN,2024-03-04 00:00:00,Review the Truck Information,tr35,NaN,NaN,None,None,125YSO,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1502,NaN,2024-03-04 00:00:00,Review the Truck Information,tr36,NaN,NaN,None,None,671NRX,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1525,NaN,2024-03-04 00:00:00,Review the Truck Information,tr37,NaN,NaN,None,None,280QHM,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1548,NaN,2024-03-04 00:00:00,Review the Truck Information,tr38,NaN,NaN,None,None,846KXL,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1593,NaN,2024-03-04 00:00:00,Review the Truck Information,tr39,NaN,NaN,None,None,152ACE,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1627,NaN,2024-03-04 00:00:00,Review the Truck Information,tr4,NaN,NaN,None,None,335QUF,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1661,NaN,2024-03-04 00:00:00,Review the Truck Information,tr40,NaN,NaN,None,None,665MJJ,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1684,NaN,2024-03-04 00:00:00,Review the Truck Information,tr41,NaN,NaN,None,None,055DSW,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1762,NaN,2024-03-04 00:00:00,Review the Truck Information,tr42,NaN,NaN,None,None,478FZE,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1818,NaN,2024-03-04 00:00:00,Review the Truck Information,tr43,NaN,NaN,None,None,516RXR,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1863,NaN,2024-03-04 00:00:00,Review the Truck Information,tr44,NaN,NaN,None,None,693VMO,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1908,NaN,2024-03-04 00:00:00,Review the Truck Information,tr45,NaN,NaN,None,None,110JHX,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1931,NaN,2024-03-04 00:00:00,Review the Truck Information,tr46,NaN,NaN,None,None,271FSE,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1987,NaN,2024-03-04 00:00:00,Review the Truck Information,tr47,NaN,NaN,None,None,249VPA,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2010,NaN,2024-03-04 00:00:00,Review the Truck Information,tr48,NaN,NaN,None,None,352PSG,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2044,NaN,2024-03-04 00:00:00,Review the Truck Information,tr49,NaN,NaN,None,None,606MXL,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2100,NaN,2024-03-04 00:00:00,Review the Truck Information,tr5,NaN,NaN,None,None,012CRA,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2167,NaN,2024-03-04 00:00:00,Review the Truck Information,tr50,NaN,NaN,None,None,731QSN,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2212,NaN,2024-03-04 00:00:00,Review the Truck Information,tr6,NaN,NaN,None,None,218IVR,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2246,NaN,2024-03-04 00:00:00,Review the Truck Information,tr7,NaN,NaN,None,None,068JIT,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2280,NaN,2024-03-04 00:00:00,Review the Truck Information,tr8,NaN,NaN,None,None,773CWA,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2336,NaN,2024-03-04 00:00:00,Review the Truck Information,tr9,NaN,NaN,None,None,358QAR,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN

In [25]:
df_final.loc[(df_final['Ocel_changed_field'].isna()) & df_final['Cargo Type'].notna(), 'Activity'] = 'Review the Cargo Information'
df_final[df_final['Activity']== 'Review the Cargo Information']

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
100,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr1,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,120122.9,Sil14
101,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr10,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,112195.7,Sil16
102,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr11,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,122522.8,Sil19
103,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr12,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,115248.0,Sil6
104,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr13,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,149062.7,Sil9
105,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr14,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,111838.1,Sil17
106,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr15,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,104991.9,Sil15
107,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr16,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,137906.9,Sil5
108,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr17,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wheat,147086.0,Sil20
109,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr18,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,133940.9,Sil11
110,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr19,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,147400.1,Sil13
111,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr2,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wheat,100643.3,Sil12
112,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr20,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,124022.0,Sil4
113,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr3,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wheat,104152.1,Sil10
114,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr4,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,145709.9,Sil8
115,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr5,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,128333.2,Sil18
116,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr6,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,111912.3,Sil7
117,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr7,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,140837.9,Sil1
118,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr8,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,122616.8,Sil2
119,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr9,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wheat,143929.8,Sil3

In [26]:
df_final

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,Lodge_Pcp1,2024-04-29 16:02:43,Lodge Pickup Plan,Pcp1,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp1,Cr4,NaN,NaN,NaN,NaN,NaN,2.0,10278.5,NaN,102064.7,NaN
1,Lodge_Pcp10,2024-04-29 10:36:01,Lodge Pickup Plan,Pcp10,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp10,Cr5,NaN,NaN,NaN,NaN,NaN,2.0,10411.3,NaN,106168.0,NaN
2,Lodge_Pcp100,2024-04-29 11:34:06,Lodge Pickup Plan,Pcp100,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp100,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10424.2,NaN,91717.3,NaN
3,Lodge_Pcp11,2024-04-29 17:13:44,Lodge Pickup Plan,Pcp11,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp11,Cr19,NaN,NaN,NaN,NaN,NaN,2.0,10252.9,NaN,93563.1,NaN
4,Lodge_Pcp12,2024-04-29 16:39:13,Lodge Pickup Plan,Pcp12,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp12,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,10420.8,NaN,100464.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN
2366,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2367,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2368,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2369,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
assign_trucks_df =df_final[df_final['Activity'] == 'Assign Truck']
assign_trucks_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
121,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,None,None,None,NaN,NaN,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
122,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Pickup Plan ID,Pcp47,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
123,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Scheduled Pickup Weight,None,None,None,NaN,5308.7,None,NaN,NaN,NaN,NaN,NaN,NaN
124,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Cargo ID,None,Cr13,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
132,assign_tr1_Pcp24,2024-05-01 14:13:49,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,None,None,None,NaN,NaN,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,assign_tr9_Pcp13,2024-05-01 15:49:52,Assign Truck,tr9,Truck being assigned for pickup,Cargo ID,None,Cr15,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
2359,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Truck Status,None,None,None,NaN,NaN,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
2360,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Pickup Plan ID,Pcp78,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
2361,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Scheduled Pickup Weight,None,None,None,NaN,5371.1,None,NaN,NaN,NaN,NaN,NaN,NaN
2362,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Cargo ID,None,Cr5,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
assign_trucks_df =df_final[df_final['Activity'] == 'Assign Truck']
assign_trucks_df=assign_trucks_df[assign_trucks_df['Object_id'].str.startswith('tr')]
assign_trucks_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
121,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,None,None,None,NaN,NaN,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
122,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Pickup Plan ID,Pcp47,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
123,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Scheduled Pickup Weight,None,None,None,NaN,5308.7,None,NaN,NaN,NaN,NaN,NaN,NaN
124,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Cargo ID,None,Cr13,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
132,assign_tr1_Pcp24,2024-05-01 14:13:49,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,None,None,None,NaN,NaN,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,assign_tr9_Pcp13,2024-05-01 15:49:52,Assign Truck,tr9,Truck being assigned for pickup,Cargo ID,None,Cr15,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
2359,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Truck Status,None,None,None,NaN,NaN,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
2360,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Pickup Plan ID,Pcp78,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
2361,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Scheduled Pickup Weight,None,None,None,NaN,5371.1,None,NaN,NaN,NaN,NaN,NaN,NaN
2362,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Cargo ID,None,Cr5,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
other_activities_df = df_final[df_final['Activity'] != 'Assign Truck']
other_activities_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,Lodge_Pcp1,2024-04-29 16:02:43,Lodge Pickup Plan,Pcp1,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp1,Cr4,NaN,NaN,NaN,NaN,NaN,2.0,10278.5,NaN,102064.7,NaN
1,Lodge_Pcp10,2024-04-29 10:36:01,Lodge Pickup Plan,Pcp10,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp10,Cr5,NaN,NaN,NaN,NaN,NaN,2.0,10411.3,NaN,106168.0,NaN
2,Lodge_Pcp100,2024-04-29 11:34:06,Lodge Pickup Plan,Pcp100,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp100,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10424.2,NaN,91717.3,NaN
3,Lodge_Pcp11,2024-04-29 17:13:44,Lodge Pickup Plan,Pcp11,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp11,Cr19,NaN,NaN,NaN,NaN,NaN,2.0,10252.9,NaN,93563.1,NaN
4,Lodge_Pcp12,2024-04-29 16:39:13,Lodge Pickup Plan,Pcp12,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp12,Cr9,NaN,NaN,NaN,NaN,NaN,2.0,10420.8,NaN,100464.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN
2366,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2367,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2368,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2369,NaN,2024-05-02 08:46:35,NaN,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
def merge_group_rows_with_field(group):
    merged_row = group.iloc[0].copy()
    for col in group.columns:
        if col not in ['Event_id', 'Activity', 'Timestamp', 'Object_id', 'Ocel_changed_field']:
            non_null_values = group[col].dropna().unique()
            if len(non_null_values) > 0:
                merged_row[col] = non_null_values[0]

    # Populate the value from 'ocel_changed_field' into the corresponding column
    for _, row in group.iterrows():
        field = row['Ocel_changed_field']
        if field in group.columns and pd.notna(row[field]):
            merged_row[field] = row[field]

    return merged_row

In [31]:
assigned = assign_trucks_df.groupby(['Event_id', 'Timestamp']).apply(merge_group_rows_with_field).reset_index(drop=True)
assigned

/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/1646235976.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  assigned = assign_trucks_df.groupby(['Event_id', 'Timestamp']).apply(merge_group_rows_with_field).reset_index(drop=True)

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,assign_tr10_Pcp28,2024-05-01 09:47:08,Assign Truck,tr10,Truck being assigned for pickup,Truck Status,Pcp28,Cr20,None,NaN,5479.6,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
1,assign_tr10_Pcp40,2024-05-01 15:36:50,Assign Truck,tr10,Truck being assigned for pickup,Truck Status,Pcp40,Cr2,None,NaN,5809.9,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
2,assign_tr10_Pcp69,2024-05-01 08:40:27,Assign Truck,tr10,Truck being assigned for pickup,Truck Status,Pcp69,Cr7,None,NaN,5147.8,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
3,assign_tr11_Pcp15,2024-05-01 15:25:29,Assign Truck,tr11,Truck being assigned for pickup,Truck Status,Pcp15,Cr3,None,NaN,5300.1,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
4,assign_tr11_Pcp48,2024-05-01 08:32:57,Assign Truck,tr11,Truck being assigned for pickup,Truck Status,Pcp48,Cr20,None,NaN,5476.2,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,assign_tr8_Pcp77,2024-05-02 12:07:16,Assign Truck,tr8,Truck being assigned for pickup,Truck Status,Pcp77,Cr13,None,NaN,5521.1,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
196,assign_tr8_Pcp80,2024-05-01 19:35:54,Assign Truck,tr8,Truck being assigned for pickup,Truck Status,Pcp80,Cr9,None,NaN,5241.5,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
197,assign_tr9_Pcp13,2024-05-01 15:49:52,Assign Truck,tr9,Truck being assigned for pickup,Truck Status,Pcp13,Cr15,None,NaN,6011.7,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
198,assign_tr9_Pcp6,2024-05-01 14:27:38,Assign Truck,tr9,Truck being assigned for pickup,Truck Status,Pcp6,Cr5,None,NaN,4895.9,Occupied,NaN,NaN,NaN,NaN,NaN,NaN
199,assign_tr9_Pcp78,2024-05-02 08:15:11,Assign Truck,tr9,Truck being assigned for pickup,Truck Status,Pcp78,Cr5,None,NaN,5371.1,Occupied,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
all_xes = pd.concat([assigned, other_activities_df]).sort_values(by='Timestamp').reset_index(drop=True)
all_xes

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,NaN,2024-03-04 00:00:00,Review the Truck Information,tr43,NaN,NaN,None,None,516RXR,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1,NaN,2024-03-04 00:00:00,Review the Truck Information,tr40,NaN,NaN,None,None,665MJJ,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2,NaN,2024-03-04 00:00:00,Review the Truck Information,tr41,NaN,NaN,None,None,055DSW,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
3,NaN,2024-03-04 00:00:00,Review the Truck Information,tr42,NaN,NaN,None,None,478FZE,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
4,NaN,2024-03-04 00:00:00,Review the Truck Information,tr34,NaN,NaN,None,None,341KDU,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,input_tally_sheet_Pcp70_tr29,2024-05-03 15:47:10,Input the Tally Sheet,tr29,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1766,print_w_ticket_Pcp70_tr29,2024-05-03 15:47:10,Print the Weighing Ticket,tr29,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1767,eval_trs_exit_tr29_Pcp70,2024-05-03 15:48:23,Evaluate the Truck Exit,tr29,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1768,NaN,2024-05-03 15:50:06,NaN,tr49,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1769,NaN,2024-05-03 15:56:08,NaN,tr29,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
all_xes.loc[(all_xes['Ocel_changed_field'] == 'Truck Status') & all_xes['Activity'].isna(), 'Activity'] = 'Prepare Reassignment'
all_xes[all_xes['Activity']== 'Prepare Reassignment']

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
204,NaN,2024-05-01 08:45:55,Prepare Reassignment,tr41,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,2024-05-01 08:46:59,Prepare Reassignment,tr49,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
221,NaN,2024-05-01 09:01:24,Prepare Reassignment,tr19,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
279,NaN,2024-05-01 09:30:34,Prepare Reassignment,tr41,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
299,NaN,2024-05-01 09:34:41,Prepare Reassignment,tr48,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,NaN,2024-05-02 14:18:56,Prepare Reassignment,tr8,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1748,NaN,2024-05-02 14:35:57,Prepare Reassignment,tr50,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1753,NaN,2024-05-02 15:24:19,Prepare Reassignment,tr29,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1768,NaN,2024-05-03 15:50:06,Prepare Reassignment,tr49,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1769,NaN,2024-05-03 15:56:08,Prepare Reassignment,tr29,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
crs = all_xes['Object_id'].str.startswith('Cr')
all_xes.loc[crs, 'Cargo ID'] = all_xes.loc[crs, 'Object_id']
all_xes

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,NaN,2024-03-04 00:00:00,Review the Truck Information,tr43,NaN,NaN,None,None,516RXR,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1,NaN,2024-03-04 00:00:00,Review the Truck Information,tr40,NaN,NaN,None,None,665MJJ,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2,NaN,2024-03-04 00:00:00,Review the Truck Information,tr41,NaN,NaN,None,None,055DSW,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
3,NaN,2024-03-04 00:00:00,Review the Truck Information,tr42,NaN,NaN,None,None,478FZE,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
4,NaN,2024-03-04 00:00:00,Review the Truck Information,tr34,NaN,NaN,None,None,341KDU,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,input_tally_sheet_Pcp70_tr29,2024-05-03 15:47:10,Input the Tally Sheet,tr29,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1766,print_w_ticket_Pcp70_tr29,2024-05-03 15:47:10,Print the Weighing Ticket,tr29,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1767,eval_trs_exit_tr29_Pcp70,2024-05-03 15:48:23,Evaluate the Truck Exit,tr29,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1768,NaN,2024-05-03 15:50:06,Prepare Reassignment,tr49,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1769,NaN,2024-05-03 15:56:08,Prepare Reassignment,tr29,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
Pcps = all_xes['Object_id'].str.startswith('Pcp')
all_xes.loc[Pcps, 'Pickup Plan ID'] = all_xes.loc[Pcps, 'Object_id']
all_xes

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID
0,NaN,2024-03-04 00:00:00,Review the Truck Information,tr43,NaN,NaN,None,None,516RXR,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
1,NaN,2024-03-04 00:00:00,Review the Truck Information,tr40,NaN,NaN,None,None,665MJJ,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
2,NaN,2024-03-04 00:00:00,Review the Truck Information,tr41,NaN,NaN,None,None,055DSW,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
3,NaN,2024-03-04 00:00:00,Review the Truck Information,tr42,NaN,NaN,None,None,478FZE,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
4,NaN,2024-03-04 00:00:00,Review the Truck Information,tr34,NaN,NaN,None,None,341KDU,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,input_tally_sheet_Pcp70_tr29,2024-05-03 15:47:10,Input the Tally Sheet,tr29,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1766,print_w_ticket_Pcp70_tr29,2024-05-03 15:47:10,Print the Weighing Ticket,tr29,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1767,eval_trs_exit_tr29_Pcp70,2024-05-03 15:48:23,Evaluate the Truck Exit,tr29,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1768,NaN,2024-05-03 15:50:06,Prepare Reassignment,tr49,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN
1769,NaN,2024-05-03 15:56:08,Prepare Reassignment,tr29,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
all_xes['Truck ID'] = all_xes['Object_id'].where(all_xes['Object_id'].str.startswith('tr'),None)
all_xes

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID
0,NaN,2024-03-04 00:00:00,Review the Truck Information,tr43,NaN,NaN,None,None,516RXR,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr43
1,NaN,2024-03-04 00:00:00,Review the Truck Information,tr40,NaN,NaN,None,None,665MJJ,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr40
2,NaN,2024-03-04 00:00:00,Review the Truck Information,tr41,NaN,NaN,None,None,055DSW,4.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr41
3,NaN,2024-03-04 00:00:00,Review the Truck Information,tr42,NaN,NaN,None,None,478FZE,2.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr42
4,NaN,2024-03-04 00:00:00,Review the Truck Information,tr34,NaN,NaN,None,None,341KDU,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,input_tally_sheet_Pcp70_tr29,2024-05-03 15:47:10,Input the Tally Sheet,tr29,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr29
1766,print_w_ticket_Pcp70_tr29,2024-05-03 15:47:10,Print the Weighing Ticket,tr29,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr29
1767,eval_trs_exit_tr29_Pcp70,2024-05-03 15:48:23,Evaluate the Truck Exit,tr29,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr29
1768,NaN,2024-05-03 15:50:06,Prepare Reassignment,tr49,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr49
1769,NaN,2024-05-03 15:56:08,Prepare Reassignment,tr29,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr29

In [37]:
trucks = all_xes[all_xes['Object_id'].str.startswith('tr')]
non_trucks = all_xes[~all_xes['Object_id'].str.startswith('tr')]
len(non_trucks)

120

In [38]:
truck_ordered = trucks.sort_values(by=['Object_id', 'Timestamp']).reset_index(drop=True)

# Reinitialize the 'pickup' column
truck_ordered['pickup'] = None

# Initialize variables to track pickups
pickup_id = 0
assigning_pickup = False
current_truck = None

# Iterate over the rows to assign pickup IDs
for idx, row in truck_ordered.iterrows():
    activity = row['Activity']
    truck_id = row['Object_id']

    if activity == "Assign Truck":
        pickup_id += 1
        assigning_pickup = True
        current_truck = truck_id
        truck_ordered.at[idx, 'pickup'] = pickup_id

    elif assigning_pickup and truck_id == current_truck:
        truck_ordered.at[idx, 'pickup'] = pickup_id
        if activity in ["Evaluate the Truck Exit"]:
            assigning_pickup = False

In [39]:
truck_ordered

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,pickup
0,NaN,2024-03-04 00:00:00,Review the Truck Information,tr1,NaN,NaN,None,None,779BOG,6.0,0.0,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr1,None
1,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,Pcp47,Cr13,None,NaN,5308.7,Occupied,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1
2,weigh_empty_truck_Pcp47_tr1,2024-05-01 10:56:05,Weigh the Empty Truck,tr1,Empty truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,11221.4,NaN,NaN,NaN,NaN,NaN,tr1,1
3,load_truck_Pcp47_tr1,2024-05-01 10:56:44,Load Truck,tr1,Truck being loaded with cargo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1
4,weigh_loaded_truck_Pcp47_tr1,2024-05-01 12:01:28,Weigh the Loaded Truck,tr1,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,16530.1,NaN,NaN,NaN,NaN,NaN,tr1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,weigh_loaded_truck_Pcp78_tr9,2024-05-02 08:36:09,Weigh the Loaded Truck,tr9,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,NaN,None,18708.9,NaN,NaN,NaN,NaN,NaN,tr9,200
1646,input_tally_sheet_Pcp78_tr9,2024-05-02 08:38:50,Input the Tally Sheet,tr9,Truck being recorded on tally sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr9,200
1647,print_w_ticket_Pcp78_tr9,2024-05-02 08:38:50,Print the Weighing Ticket,tr9,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr9,200
1648,eval_trs_exit_tr9_Pcp78,2024-05-02 08:40:28,Evaluate the Truck Exit,tr9,Truck being evaluated for exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr9,200
1649,NaN,2024-05-02 08:46:35,Prepare Reassignment,tr9,NaN,Truck Status,None,None,None,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None

In [40]:
pp_cr_ids = truck_ordered.dropna(subset=['pickup']).drop_duplicates(subset=['pickup'])[['pickup', 'Pickup Plan ID','Cargo ID']]
pp_cr_ids

     pickup Pickup Plan ID Cargo ID
1         1          Pcp47     Cr13
9         2          Pcp24      Cr9
17        3          Pcp46     Cr16
25        4          Pcp96      Cr8
34        5          Pcp69      Cr7
...     ...            ...      ...
1609    196          Pcp80      Cr9
1617    197          Pcp77     Cr13
1626    198           Pcp6      Cr5
1634    199          Pcp13     Cr15
1642    200          Pcp78      Cr5

[200 rows x 3 columns]

In [41]:
alltrucks_df = pd.merge(truck_ordered, pp_cr_ids, on='pickup', how='outer', suffixes=('', '_filled'))
alltrucks_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,...,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,pickup,Pickup Plan ID_filled,Cargo ID_filled
0,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,Pcp47,Cr13,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47,Cr13
1,weigh_empty_truck_Pcp47_tr1,2024-05-01 10:56:05,Weigh the Empty Truck,tr1,Empty truck getting weighed,Truck Weight,None,None,None,NaN,...,11221.4,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47,Cr13
2,load_truck_Pcp47_tr1,2024-05-01 10:56:44,Load Truck,tr1,Truck being loaded with cargo,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47,Cr13
3,weigh_loaded_truck_Pcp47_tr1,2024-05-01 12:01:28,Weigh the Loaded Truck,tr1,Loaded truck getting weighed,Truck Weight,None,None,None,NaN,...,16530.1,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47,Cr13
4,print_w_ticket_Pcp47_tr1,2024-05-01 12:05:09,Print the Weighing Ticket,tr1,Truck receiving weighing ticket,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47,Cr13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,NaN,2024-05-02 14:18:56,Prepare Reassignment,tr8,NaN,Truck Status,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr8,None,NaN,NaN
1646,NaN,2024-03-04 00:00:00,Review the Truck Information,tr9,NaN,NaN,None,None,358QAR,6.0,...,0.0,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN,NaN
1647,NaN,2024-05-01 15:08:03,Prepare Reassignment,tr9,NaN,Truck Status,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN,NaN
1648,NaN,2024-05-01 16:10:01,Prepare Reassignment,tr9,NaN,Truck Status,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN,NaN
1649,NaN,2024-05-02 08:46:35,Prepare Reassignment,tr9,NaN,Truck Status,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN,NaN

In [42]:
alltrucks_df['Cargo ID'] = alltrucks_df['Cargo ID'].fillna(alltrucks_df['Cargo ID_filled'])
alltrucks_df.drop(columns=['Cargo ID_filled'], inplace=True)
alltrucks_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,...,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,pickup,Pickup Plan ID_filled
0,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,Pcp47,Cr13,None,NaN,...,Occupied,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
1,weigh_empty_truck_Pcp47_tr1,2024-05-01 10:56:05,Weigh the Empty Truck,tr1,Empty truck getting weighed,Truck Weight,None,Cr13,None,NaN,...,None,11221.4,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
2,load_truck_Pcp47_tr1,2024-05-01 10:56:44,Load Truck,tr1,Truck being loaded with cargo,NaN,NaN,Cr13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
3,weigh_loaded_truck_Pcp47_tr1,2024-05-01 12:01:28,Weigh the Loaded Truck,tr1,Loaded truck getting weighed,Truck Weight,None,Cr13,None,NaN,...,None,16530.1,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
4,print_w_ticket_Pcp47_tr1,2024-05-01 12:05:09,Print the Weighing Ticket,tr1,Truck receiving weighing ticket,NaN,NaN,Cr13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,NaN,2024-05-02 14:18:56,Prepare Reassignment,tr8,NaN,Truck Status,None,NaN,None,NaN,...,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr8,None,NaN
1646,NaN,2024-03-04 00:00:00,Review the Truck Information,tr9,NaN,NaN,None,NaN,358QAR,6.0,...,Available,0.0,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN
1647,NaN,2024-05-01 15:08:03,Prepare Reassignment,tr9,NaN,Truck Status,None,NaN,None,NaN,...,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN
1648,NaN,2024-05-01 16:10:01,Prepare Reassignment,tr9,NaN,Truck Status,None,NaN,None,NaN,...,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN
1649,NaN,2024-05-02 08:46:35,Prepare Reassignment,tr9,NaN,Truck Status,None,NaN,None,NaN,...,Available,NaN,NaN,NaN,NaN,NaN,NaN,tr9,None,NaN

In [43]:
non_trucks['Pickup Plan ID_filled'] = None
groupPP = non_trucks['Pickup Plan ID_filled'].isna() & non_trucks['Pickup Plan ID'].notna()
non_trucks.loc[groupPP, 'Pickup Plan ID_filled'] = non_trucks.loc[groupPP, 'Pickup Plan ID']
non_trucks

/var/folders/sh/cf1_530j6j988hhy49dfwcn40000gn/T/ipykernel_20367/2496304823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_trucks['Pickup Plan ID_filled'] = None

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,Pickup Plan ID_filled
38,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr14,NaN,None,NaN,Cr14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,111838.1,Sil17,None,None
39,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr1,NaN,None,NaN,Cr1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,120122.9,Sil14,None,None
41,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr17,NaN,None,NaN,Cr17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wheat,147086.0,Sil20,None,None
43,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr10,NaN,None,NaN,Cr10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corn,112195.7,Sil16,None,None
44,NaN,2024-03-04 00:00:00,Review the Cargo Information,Cr19,NaN,None,NaN,Cr19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,147400.1,Sil13,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Lodge_Pcp37,2024-04-30 09:33:26,Lodge Pickup Plan,Pcp37,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp37,Cr20,NaN,NaN,NaN,NaN,NaN,2.0,10831.7,NaN,70689.5,NaN,None,Pcp37
166,Lodge_Pcp75,2024-04-30 09:48:21,Lodge Pickup Plan,Pcp75,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp75,Cr14,NaN,NaN,NaN,NaN,NaN,2.0,11362.6,NaN,55629.0,NaN,None,Pcp75
167,Lodge_Pcp62,2024-04-30 11:13:27,Lodge Pickup Plan,Pcp62,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp62,Cr15,NaN,NaN,NaN,NaN,NaN,2.0,10123.2,NaN,39322.9,NaN,None,Pcp62
168,Lodge_Pcp50,2024-04-30 11:14:56,Lodge Pickup Plan,Pcp50,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp50,Cr17,NaN,NaN,NaN,NaN,NaN,2.0,11828.4,NaN,77221.3,NaN,None,Pcp50
169,Lodge_Pcp77,2024-04-30 12:06:41,Lodge Pickup Plan,Pcp77,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp77,Cr13,NaN,NaN,NaN,NaN,NaN,2.0,10804.9,NaN,104910.4,NaN,None,Pcp77

In [44]:
all_df = pd.concat([alltrucks_df, non_trucks], ignore_index=True)
all_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Ocel_changed_field,Pickup Plan ID,Cargo ID,LPT,Axles,...,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,pickup,Pickup Plan ID_filled
0,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Truck Status,Pcp47,Cr13,None,NaN,...,Occupied,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
1,weigh_empty_truck_Pcp47_tr1,2024-05-01 10:56:05,Weigh the Empty Truck,tr1,Empty truck getting weighed,Truck Weight,None,Cr13,None,NaN,...,None,11221.4,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
2,load_truck_Pcp47_tr1,2024-05-01 10:56:44,Load Truck,tr1,Truck being loaded with cargo,NaN,NaN,Cr13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
3,weigh_loaded_truck_Pcp47_tr1,2024-05-01 12:01:28,Weigh the Loaded Truck,tr1,Loaded truck getting weighed,Truck Weight,None,Cr13,None,NaN,...,None,16530.1,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
4,print_w_ticket_Pcp47_tr1,2024-05-01 12:05:09,Print the Weighing Ticket,tr1,Truck receiving weighing ticket,NaN,NaN,Cr13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,Lodge_Pcp37,2024-04-30 09:33:26,Lodge Pickup Plan,Pcp37,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp37,Cr20,NaN,NaN,...,NaN,NaN,2.0,10831.7,NaN,70689.5,NaN,None,NaN,Pcp37
1766,Lodge_Pcp75,2024-04-30 09:48:21,Lodge Pickup Plan,Pcp75,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp75,Cr14,NaN,NaN,...,NaN,NaN,2.0,11362.6,NaN,55629.0,NaN,None,NaN,Pcp75
1767,Lodge_Pcp62,2024-04-30 11:13:27,Lodge Pickup Plan,Pcp62,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp62,Cr15,NaN,NaN,...,NaN,NaN,2.0,10123.2,NaN,39322.9,NaN,None,NaN,Pcp62
1768,Lodge_Pcp50,2024-04-30 11:14:56,Lodge Pickup Plan,Pcp50,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp50,Cr17,NaN,NaN,...,NaN,NaN,2.0,11828.4,NaN,77221.3,NaN,None,NaN,Pcp50
1769,Lodge_Pcp77,2024-04-30 12:06:41,Lodge Pickup Plan,Pcp77,Pickup plan being lodged,Cargo stock weight(scheduled),Pcp77,Cr13,NaN,NaN,...,NaN,NaN,2.0,10804.9,NaN,104910.4,NaN,None,NaN,Pcp77

In [45]:
all_df.drop(columns=['Ocel_changed_field','Pickup Plan ID'],inplace=True)
all_df.rename(columns={'Pickup Plan ID_filled': 'Pickup Plan ID'}, inplace=True)

In [46]:
all_df['Cargo ID'] = all_df['Cargo ID'].replace(['', ' '], pd.NA)
all_df['Cargo ID'] = all_df.groupby('pickup')['Cargo ID'].transform(lambda x: x.ffill().bfill())
all_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,pickup,Pickup Plan ID
0,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Cr13,None,NaN,5308.7,Occupied,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
1,weigh_empty_truck_Pcp47_tr1,2024-05-01 10:56:05,Weigh the Empty Truck,tr1,Empty truck getting weighed,Cr13,None,NaN,NaN,None,11221.4,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
2,load_truck_Pcp47_tr1,2024-05-01 10:56:44,Load Truck,tr1,Truck being loaded with cargo,Cr13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
3,weigh_loaded_truck_Pcp47_tr1,2024-05-01 12:01:28,Weigh the Loaded Truck,tr1,Loaded truck getting weighed,Cr13,None,NaN,NaN,None,16530.1,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
4,print_w_ticket_Pcp47_tr1,2024-05-01 12:05:09,Print the Weighing Ticket,tr1,Truck receiving weighing ticket,Cr13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,Lodge_Pcp37,2024-04-30 09:33:26,Lodge Pickup Plan,Pcp37,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10831.7,NaN,70689.5,NaN,None,NaN,Pcp37
1766,Lodge_Pcp75,2024-04-30 09:48:21,Lodge Pickup Plan,Pcp75,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,11362.6,NaN,55629.0,NaN,None,NaN,Pcp75
1767,Lodge_Pcp62,2024-04-30 11:13:27,Lodge Pickup Plan,Pcp62,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10123.2,NaN,39322.9,NaN,None,NaN,Pcp62
1768,Lodge_Pcp50,2024-04-30 11:14:56,Lodge Pickup Plan,Pcp50,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,11828.4,NaN,77221.3,NaN,None,NaN,Pcp50
1769,Lodge_Pcp77,2024-04-30 12:06:41,Lodge Pickup Plan,Pcp77,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10804.9,NaN,104910.4,NaN,None,NaN,Pcp77

In [47]:
crs1 = all_df['Object_id'].str.startswith('Cr')
all_df.loc[crs1, 'Cargo ID'] = all_df.loc[crs1, 'Object_id']
all_df

,Event_id,Timestamp,Activity,Object_id,E2O_qualifier,Cargo ID,LPT,Axles,Scheduled Pickup Weight,Truck Status,Truck Weight,Num of trucks,Total pickup weight,Cargo Type,Cargo stock weight(scheduled),Silo ID,Truck ID,pickup,Pickup Plan ID
0,assign_tr1_Pcp47,2024-05-01 10:49:20,Assign Truck,tr1,Truck being assigned for pickup,Cr13,None,NaN,5308.7,Occupied,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
1,weigh_empty_truck_Pcp47_tr1,2024-05-01 10:56:05,Weigh the Empty Truck,tr1,Empty truck getting weighed,Cr13,None,NaN,NaN,None,11221.4,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
2,load_truck_Pcp47_tr1,2024-05-01 10:56:44,Load Truck,tr1,Truck being loaded with cargo,Cr13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
3,weigh_loaded_truck_Pcp47_tr1,2024-05-01 12:01:28,Weigh the Loaded Truck,tr1,Loaded truck getting weighed,Cr13,None,NaN,NaN,None,16530.1,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
4,print_w_ticket_Pcp47_tr1,2024-05-01 12:05:09,Print the Weighing Ticket,tr1,Truck receiving weighing ticket,Cr13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tr1,1,Pcp47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,Lodge_Pcp37,2024-04-30 09:33:26,Lodge Pickup Plan,Pcp37,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10831.7,NaN,70689.5,NaN,None,NaN,Pcp37
1766,Lodge_Pcp75,2024-04-30 09:48:21,Lodge Pickup Plan,Pcp75,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,11362.6,NaN,55629.0,NaN,None,NaN,Pcp75
1767,Lodge_Pcp62,2024-04-30 11:13:27,Lodge Pickup Plan,Pcp62,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10123.2,NaN,39322.9,NaN,None,NaN,Pcp62
1768,Lodge_Pcp50,2024-04-30 11:14:56,Lodge Pickup Plan,Pcp50,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,11828.4,NaN,77221.3,NaN,None,NaN,Pcp50
1769,Lodge_Pcp77,2024-04-30 12:06:41,Lodge Pickup Plan,Pcp77,Pickup plan being lodged,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10804.9,NaN,104910.4,NaN,None,NaN,Pcp77

In [48]:
all_df.to_csv('all.csv',index=False)